Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.insert_key = false
  config.vm.network "forwarded_port", guest: 3002, host: 3002
  config.vm.network "private_network", ip: "192.168.56.215"
  config.vm.synced_folder ".", "/var/www/project"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y g++
    curl -sL https://deb.nodesource.com/setup_6.x| sudo -E bash -
    sudo apt-get install -y nodejs
    sudo su vagrant
    cd /var/www/project/server
    sudo npm install
  SHELL
end
